"""Update studyDeck

Revision ID: 18af69843c99
Revises: 7afa0ad1d3dc
Create Date: 2024-10-27 20:42:37.336517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18af69843c99'
down_revision = '7afa0ad1d3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=70), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=9), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('study_deck', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
