"""Add CardTracker

Revision ID: 485d9e0c6b57
Revises: 18af69843c99
Create Date: 2024-11-01 19:28:57.548702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485d9e0c6b57'
down_revision = '18af69843c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_card', schema=None) as batch_op:
        batch_op.drop_column('mastery_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mastery_level', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
