"""Flashcards

Revision ID: 7afa0ad1d3dc
Revises: efe0bb102a2e
Create Date: 2024-10-13 09:30:41.045539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afa0ad1d3dc'
down_revision = 'efe0bb102a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'study_deck', ['deck_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deck_id')

    # ### end Alembic commands ###
